import type {Skill} from "@portfolio/types"

export const skills: Skill[] = [
    {
      name: "Next.js",
      icon: '/next.svg',
      description: "I use Next.js as my main frontend framework",
      level: 0.9,
      usage: 1,
      lBarColor: "fill-lime-600",
      lTextColor: "fill-orange-500",
      uBarColor: "fill-blue-600",
      uTextColor: "fill-red-500",
    },
    {
      name: "Redux",
      icon: '/redux.svg',
      description: "I rely on Redux to manage complex state in large React applications",
      level: 0.6,
      usage: 0.7,
      lBarColor: "fill-lime-600",
      lTextColor: "fill-orange-500",
      uBarColor: "fill-blue-600",
      uTextColor: "fill-red-500",
    },
    {
      name: "Express",
      icon: '/express.svg',
      description: "Server Framework",
      level: 0.8,
      usage: 1,
      lBarColor: "fill-lime-600",
      lTextColor: "fill-orange-500",
      uBarColor: "fill-blue-600",
      uTextColor: "fill-red-500",
    },
    {
      name: "Socket.io",
      icon: '/socketio.svg',
      description: "Server Framework",
      level: 0.8,
      usage: 1,
      lBarColor: "fill-lime-600",
      lTextColor: "fill-orange-500",
      uBarColor: "fill-blue-600",
      uTextColor: "fill-red-500",
    },
    {
      name: "Postgres",
      icon: '/postgres.svg',
      description: "Database",
      level: 0.8,
      usage: 1,
      lBarColor: "fill-lime-600",
      lTextColor: "fill-orange-500",
      uBarColor: "fill-blue-600",
      uTextColor: "fill-red-500",
    },
    {
      name: "MongoDB",
      icon: '/mongodb.svg',
      description: "Database",
      level: 0.8,
      usage: 1,
      lBarColor: "fill-lime-600",
      lTextColor: "fill-orange-500",
      uBarColor: "fill-blue-600",
      uTextColor: "fill-red-500",
    },
    {
      name: "Prisma",
      icon: '/prisma.svg',
      description: "Database",
      level: 0.8,
      usage: 1,
      lBarColor: "fill-lime-600",
      lTextColor: "fill-orange-500",
      uBarColor: "fill-blue-600",
      uTextColor: "fill-red-500",
    },
    {
      name: "tRPC",
      icon: '/trpc.svg',
      description: "Server Framework",
      level: 0.8,
      usage: 1,
      lBarColor: "fill-lime-600",
      lTextColor: "fill-orange-500",
      uBarColor: "fill-blue-600",
      uTextColor: "fill-red-500",
    },
    {
      name: "Redis",
      icon: "/redis.svg",
      description: "Cache",
      level: 0.8,
      usage: 1,
      lBarColor: "fill-lime-600",
      lTextColor: "fill-orange-500",
      uBarColor: "fill-blue-600",
      uTextColor: "fill-red-500",
    },
    {
      name: "Nextauth",
      icon: "https://next-auth.js.org/img/logo/logo-sm.png",
      description: "Authentication",
      level: 0.8,
      usage: 1,
      lBarColor: "fill-lime-600",
      lTextColor: "fill-orange-500",
      uBarColor: "fill-blue-600",
      uTextColor: "fill-red-500",
    },
    {
      name: "Docker",
      icon: "/docker.svg",
      description: "Containerization",
      level: 0.5,
      usage: 0.25,
      lBarColor: "fill-lime-600",
      lTextColor: "fill-orange-500",
      uBarColor: "fill-blue-600",
      uTextColor: "fill-red-500",
    },
    {
      name: "Typescript",
      icon: "/typescript.svg",
      description: "Language",
      level: 0.8,
      usage: 1,
      lBarColor: "fill-lime-600",
      lTextColor: "fill-orange-500",
      uBarColor: "fill-blue-600",
      uTextColor: "fill-red-500",
    },
    {
      name: "Turborepo",
      icon: "https://turbo.build/images/docs/repo/repo-hero-logo-dark.svg",
      description: "Turborepo",
      level: 0.8,
      usage: 1,
      lBarColor: "fill-lime-600",
      lTextColor: "fill-orange-500",
      uBarColor: "fill-blue-600",
      uTextColor: "fill-red-500",
    },
    {
      name: "Aws s3",
      icon: "/s3.svg",
      description: "Storage",
      level: 0.8,
      usage: 1,
      lBarColor: "fill-lime-600",
      lTextColor: "fill-orange-500",
      uBarColor: "fill-blue-600",
      uTextColor: "fill-red-500",
    },
    {
      name: "Tailwind",
      icon: "/tailwind.svg",
      description: "CSS Framework",
      level: 0.8,
      usage: 1,
      lBarColor: "fill-lime-600",
      lTextColor: "fill-orange-500",
      uBarColor: "fill-blue-600",
      uTextColor: "fill-red-500",
    },
    {
      name: "css",
      icon: "/css.svg",
      description: "CSS",
      level: 0.8,
      usage: 1,
      lBarColor: "fill-lime-600",
      lTextColor: "fill-orange-500",
      uBarColor: "fill-blue-600",
      uTextColor: "fill-red-500",
    }
  ]